services:
  db:
    build: ./db-fixtures
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/test_db
    depends_on:
      - db
